on: workflow_dispatch
name: Download_Artifacts
jobs:
#  download:    
#    steps:
#    - name: download
#      uses: actions/download-artifact@v4
#        github-token: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
#        repository:actions/toolkit
#        run-id:1234

  steps:
   runs-on: macos-latest
    - uses:actions/download-artifact@v4
    - name:Display structure of downloaded files
    run:ls -R
